server:
  port: 8070
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgresql:5432/account
    # url: jdbc:postgresql://localhost:5432/account
    username: postgres
    password: admin

  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect



  flyway:
    baseline-on-migrate: true
    enabled: true
    user: postgres
    password: admin
    baseline-description: Initial version
    baseline-version: 0

eureka:
  client:
    service-url:
     defaultZone: http://discovery-service:8761/eurekaDoctorCredentialRepo
      # defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

application:
  config:
    expertise-url: http://localhost:8222/api/v1/expertise