server:
  port: 8071
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgresql:5432/booking-service
#    url: jdbc:postgresql://postgresql:5432/booking
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
    livereload:
      enabled: true
    remote:
      restart:
        enabled: true
  flyway:
    baseline-on-migrate: true
    enabled: true
    user: postgres
    password: admin
    baseline-description: Initial version
    baseline-version: 0
eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka
  instance:
    prefer-ip-address: true

application:
  config:
    schedule-url: http://api-gateway:8222/api/v1/schedule