server:
  port: 8076
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgresql:5432/payment
    # url: jdbc:postgresql://localhost:5432/payment
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    enabled: true
    user: postgres
    password: admin
    baseline-description: Initial version
    baseline-version: 0
  kafka:
    bootstrap-servers: kafka:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        # KHÔNG gửi thông tin class java trong header message
        spring.json.add.type.headers: false 
    consumer:
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer 
      # Lưu ý: Dùng StringDeserializer ở consumer để nhận chuỗi JSON thô, 
      # sau đó tự map bằng ObjectMapper trong code cho an toàn và dễ debug.
      enable-auto-commit: true   # ✅ Auto commit offset
      properties:
        max.poll.records: 1
        max.poll.interval.ms: 300000

    listener:
      ack-mode: record
      concurrency: 1  # ✅ Process 1 message at a time


eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka
  instance:
    prefer-ip-address: true