server:
  port: 8077
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgresql:5432/schedule
    # url: jdbc:postgresql://localhost:5432/schedule
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
    livereload:
      enabled: true
    remote:
      restart:
        enabled: true
  flyway:
    baseline-on-migrate: true
    enabled: true
    user: postgres
    password: admin
    baseline-description: Initial version
    baseline-version: 0
eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka
  instance:
    prefer-ip-address: true

application:
  config:
    expertise-url: http://api-gateway:8222/api/v1/expertise
    package-service-url: http://api-gateway:8222/api/v1/packages-services
    clinic-service-url: http://api-gateway:8222/api/v1/clinics



